from enum import StrEnum


class InvestigationStatus(StrEnum):
    INITIALIZED = "INITIALIZED"
    PREPARING = "PREPARING"
    SEARCHING = "SEARCHING"
    VETTING_MANDATORY = "VETTING_MANDATORY"
    SELECTING_ADAPTIVE_EXPERIMENT = "SELECTING_ADAPTIVE_EXPERIMENT"
    WAITING_FOR_CRITIC = "WAITING_FOR_CRITIC"
    RUNNING_TOOL = "RUNNING_TOOL"
    UPDATING_EVIDENCE = "UPDATING_EVIDENCE"
    READY_TO_LOCK = "READY_TO_LOCK"
    RESULT_LOCKED = "RESULT_LOCKED"
    REVEALED = "REVEALED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"


TERMINAL_STATUSES = frozenset(
    {
        InvestigationStatus.RESULT_LOCKED,
        InvestigationStatus.REVEALED,
        InvestigationStatus.INSUFFICIENT_EVIDENCE,
        InvestigationStatus.REJECTED,
        InvestigationStatus.FAILED,
        InvestigationStatus.BUDGET_EXHAUSTED,
    }
)


class LockState(StrEnum):
    GROUND_TRUTH_LOCKED = "GROUND_TRUTH_LOCKED"
    RESULT_LOCKED = "RESULT_LOCKED"
    CATALOG_REVEALED = "CATALOG_REVEALED"


class Disposition(StrEnum):
    NO_CREDIBLE_PERIODIC_SIGNAL = "NO_CREDIBLE_PERIODIC_SIGNAL"
    TRANSIT_LIKE_SIGNAL = "TRANSIT_LIKE_SIGNAL"
    PLANETARY_INTERPRETATION_WEAK = "PLANETARY_INTERPRETATION_WEAK"
    PLANETARY_INTERPRETATION_PLAUSIBLE = "PLANETARY_INTERPRETATION_PLAUSIBLE"
    PLANETARY_INTERPRETATION_SURVIVES_IMPLEMENTED_VETTING = (
        "PLANETARY_INTERPRETATION_SURVIVES_IMPLEMENTED_VETTING"
    )
    PLANETARY_INTERPRETATION_REJECTED = "PLANETARY_INTERPRETATION_REJECTED"
    INCONCLUSIVE_ADDITIONAL_DATA_REQUIRED = "INCONCLUSIVE_ADDITIONAL_DATA_REQUIRED"


class ToolStatus(StrEnum):
    SUCCESS = "SUCCESS"
    NO_EVIDENCE = "NO_EVIDENCE"
    INDETERMINATE = "INDETERMINATE"
    PRECONDITION_FAILED = "PRECONDITION_FAILED"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    FAILED = "FAILED"


class CriticVerdict(StrEnum):
    APPROVE = "APPROVE"
    REVISE = "REVISE"
    VETO = "VETO"


class InformationValue(StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class Priority(StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class ToolExecutionStatus(StrEnum):
    PREPARED = "PREPARED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class HarnessFailureKind(StrEnum):
    INVALID_MODEL_OUTPUT = "INVALID_MODEL_OUTPUT"
    OUTPUT_TRUNCATED = "OUTPUT_TRUNCATED"
    MODEL_TIMEOUT = "MODEL_TIMEOUT"
    MODEL_PROVIDER_FAILURE = "MODEL_PROVIDER_FAILURE"
    UNKNOWN_ACTION = "UNKNOWN_ACTION"
    UNAVAILABLE_ACTION = "UNAVAILABLE_ACTION"
    MALFORMED_PARAMETERS = "MALFORMED_PARAMETERS"
    UNAUTHORIZED_ACTION = "UNAUTHORIZED_ACTION"
    PRECONDITION_FAILED = "PRECONDITION_FAILED"
    REPEATED_ACTION = "REPEATED_ACTION"
    TOOL_TIMEOUT = "TOOL_TIMEOUT"
    TOOL_INFRASTRUCTURE_FAILURE = "TOOL_INFRASTRUCTURE_FAILURE"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
